kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: tls-cert
spec:
  subject:
    organizations:
    - aws
  commonName: petclinic.bitsncloud.com # need to replace with your custom domain name
  dnsNames:
    - petclinic.bitsncloud.com # need to replace with your custom domain name
  duration: 2160h0m0s
  issuerRef:
    group: awspca.cert-manager.io
    kind: AWSPCAClusterIssuer
    name: aws-pca-issuer
  renewBefore: 360h0m0s
  secretName: tls-secret
  usages:
    - server auth
    - client auth
  privateKey:
    algorithm: "RSA"
    size: 2048