apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: cert-manager
data:
  accesskey: QUtJQVI0UkpVTlNPTEZEQktWU0w=
  secretkey: eG5VQzZOQjh4TjYrQWlUdXdvTjYvd2FOc2FhUDZQdit5bExkVWE4Uw==
  region: dXMtZWFzdC0x
  arn: YXJuOmF3czphY20tcGNhOnVzLWVhc3QtMToxMzAwMTAwODI0NjA6Y2VydGlmaWNhdGUtYXV0aG9yaXR5L2MxZDZiZDkzLTI1MTctNDQzMy1iNTI1LWMyZTQwMjA1MGVlOQ==

# apiVersion: v1
# kind: Secret
# metadata:
#   name: aws-credentials
#   namespace: cert-manager
# data:
#   AWS_ACCESS_KEY_ID: QUtJQVI0UkpVTlNPTEZEQktWU0w=
#   AWS_SECRET_ACCESS_KEY: eG5VQzZOQjh4TjYrQWlUdXdvTjYvd2FOc2FhUDZQdit5bExkVWE4Uw==